#!/usr/bin/env python

import sys, struct

if(len(sys.argv) < 2):
	sys.exit("please specify a file (or - for stdin)")
elif(sys.argv[1] == '-'):
	f = sys.stdin;
elif(sys.argv[1]):
	f = open(sys.argv[1], "rb")
else:
	sys.exit("please specify a file (or - for stdin)")

addr = 0
while True:
	bytes = f.read(4)
	if not bytes:
		break
	cksum = 4
	cksum += addr & 0xFF
	cksum += (addr & 0xFF00) >> 8
	cksum += sum(struct.unpack('bbbb', bytes))
	cksum = -cksum
	word = struct.unpack('I', bytes)[0]
	print ":04%04X00%08X%02X" % (addr, word, cksum & 0xFF)
	addr += 1