#!/usr/bin/env python

import sys, struct

if(len(sys.argv) < 2):
	sys.exit("please specify a file (or - for stdin)")
elif(sys.argv[1] == '-'):
	f = sys.stdin;
elif(sys.argv[1]):
	f = open(sys.argv[1], "rb")
else:
	sys.exit("please specify a file (or - for stdin)")

print """WIDTH=32;
DEPTH=16384;

ADDRESS_RADIX=UNS;
DATA_RADIX=HEX;

CONTENT BEGIN"""

addr = 0
while True:
	bytes = f.read(4)
	if not bytes:
		break
	word = struct.unpack('I', bytes)[0]
	print "\t%d\t:\t%08X;" % (addr, word)
	addr += 1

print "\t[%d..16383]:\t00000000;" % addr
print "END;"
